name: Invoke updateFiles on deployment managed by Cloudsoft AMP

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke updateFiles effector using curl
        env:
          AMP_PASSWORD: $
        run: |
          curl -k -u admin:$ -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' http://localhost:8081/v1/applications/hjvt4r8ckz/entities/lfxptac8n1/effectors/updateFiles
